print("Hello and welcome to Krista's Halloweeny MadLib!")

holiday_1 = input("Enter a holiday, and press enter: ")
person_1 = input ("Enter a person's name, and press enter: ")
action_1 = input("Enter an action: ")
person_2 = input ("Enter a person's name: ")
action_2 = input ("Enter an action: ")
person_3 = input("Enter a person's name: ")
place_1 = input ("Enter a place: ")
food = input("Enter a food: ")
person_4 = input("Enter a person's name: ")
place_2 = input ("Enter a place: ")
bug = input("Enter the name of a bug: ")
thing = input("Enter a thing: ")
person_5 = input("Enter a person's name: ")
person_6 = input ("Enter a person's name: ")
feeling = input("Enter a feeling: ")
holiday_2 = input("Enter a holiday: ")
person_7 = input("Enter a person's name: ")

print(f"It's {holiday_1}! {person_1} is coming over to get ready to {action_1} with me! {person_2} helped us {action_2} pumpkins, and now {person_3} and I are going to put them {place_1}. We are full after eating {food}, and are ready to go now! {person_4} told us to watch out for the {place_2} down the street because it is scary with {bug}webs and broken {thing}. It's the house where {person_5} and {person_6} live! But I'm not {feeling}! Happy {holiday_2} to everyone from {person_7}!")
